#!/bin/bash

cat <<- EOF > /etc/logrotate.d/sms
/var/log/asterisk/sms_web_hook.log{
	size 50M
	missingok
	rotate 5
	notifempty
	sharedscripts
	dateext
	create 0640 asterisk asterisk
	su asterisk asterisk
}
EOF
