CREATE TABLE call_ai_analysis (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    call_id BIGINT UNSIGNED NOT NULL,
    call_type ENUM('inbound', 'outbound') NOT NULL,
    id_campaign BIGINT UNSIGNED NOT NULL,
    campaign_name VARCHAR(150) NOT NULL DEFAULT '',
    id_agente BIGINT UNSIGNED NULL,
    agente VARCHAR(150) NOT NULL DEFAULT '',
    numero VARCHAR(40) NOT NULL DEFAULT '',
    fecha_llamada DATETIME NOT NULL,
    duracion_segundos INT UNSIGNED NOT NULL DEFAULT 0,
    grabacion VARCHAR(255) NOT NULL DEFAULT '',
    processing_status ENUM('pendiente', 'procesando', 'listo', 'error', 'omitido') NOT NULL DEFAULT 'pendiente',
    processing_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
    processing_error TEXT NULL,
    provider VARCHAR(80) NOT NULL DEFAULT 'faster-whisper-local',
    model_name VARCHAR(80) NOT NULL DEFAULT 'tiny',
    transcription_language VARCHAR(20) NOT NULL DEFAULT 'es',
    transcription_text MEDIUMTEXT NULL,
    transcription_confidence DECIMAL(5,4) NULL,
    sentiment_label ENUM('positivo', 'neutro', 'negativo', 'mixto', 'sin_dato') NOT NULL DEFAULT 'sin_dato',
    sentiment_score DECIMAL(6,4) NULL,
    sentiment_summary TEXT NULL,
    analyzed_by_rule VARCHAR(80) NOT NULL DEFAULT 'local-v1',
    requested_by BIGINT UNSIGNED NULL,
    processing_started_at DATETIME NULL,
    processing_duration_seconds INT UNSIGNED NULL,
    transcription_seconds_per_minute DECIMAL(10,2) NULL,
    processed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_call_ai_analysis_call (call_id, call_type),
    KEY idx_call_ai_analysis_status (processing_status),
    KEY idx_call_ai_analysis_campaign (id_campaign, call_type),
    KEY idx_call_ai_analysis_fecha (fecha_llamada),
    KEY idx_call_ai_analysis_processed (processed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;